### ISSUE TITLE
【readme】起動方法について追記

### ISSUE THREAD

**Issue by ir77** [jphacks/KB_01#79]
gem, podなど

**Comment by ha1f** [comment]
僕の環境は

``` bash
gem --version
```

> 2.4.5.1

``` bash
pod --version
```

> 0.39.0

``` bash
ruby --version
```

> ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

でした

**Comment by ir77** [comment]
gem 

> 2.0.14

pod

> 0.39.0

ruby

> ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

な感じだったわ。

**Comment by ytsk** [comment]
ワイはるふと全く同じ環境だった模様

**Comment by ir77** [comment]
ワイ遅れてるぅ

**Comment by ha1f** [comment]
終了したのでclose
