### ISSUE TITLE
【readme】対応していないデバイス、未実装の機能の明記

### ISSUE THREAD

**Issue by ir77** [jphacks/KB_01#80]

**Comment by ha1f** [comment]
iPhone6, 6 Plus, 6s, 6s Plusに対応？

**Comment by ir77** [comment]
そのはず

**Comment by ir77** [comment]
あー、シミュレータも同じだっけ？いま移動中だからrunできない。。

**Comment by ha1f** [comment]
シミュレータは6, 6sのみですね
Plus系はシミュレータだとずれます・・・

**Comment by ir77** [comment]
なるほど。
実機はよしのは6sだっけ？6と6 Plusは未確認だよね？

**Comment by ha1f** [comment]
6実機使えませんでした

**Comment by ir77** [comment]
じゃあ
・シミュレータ: 6, 6s
・実機: 6s, 6s Plus
対応って感じか

**Comment by ha1f** [comment]
実機 6Plusは動きそうですけど未確認ですね・・・

6sと6s Plusで動くの謎すぎる・・・笑

**Comment by ir77** [comment]
未確認は怖いからとりあえず避けておくか…。
謎すぎるよね。。

**Comment by ysakuragi16** [comment]
実機僕6ですけど大丈夫ですよ

**Comment by ir77** [comment]
混乱してきたw

**Comment by ha1f** [comment]
母親のiPhone 6実機でレイアウト崩れてますね・・・

iOS 9.1

**Comment by ir77** [comment]
実機6でコンフリクトしてるやんw

**Comment by ysakuragi16** [comment]
まじっすか

**Comment by ha1f** [comment]
妹の実機6で動作しました

**Comment by ysakuragi16** [comment]
母親のが悪い？

**Comment by ir77** [comment]
はるふ母phone6が謎な感じか。。

**Comment by ha1f** [comment]
あ、設定→画面表示と明るさ、から「表示」が
「標準」「拡大」によって違うっぽいです！

母のは拡大になっているので、違うっぽいですね！妹のは標準なのでそのまま動きました

うっちーさんの6s plus実機ってどうなってますか？

**Comment by ysakuragi16** [comment]
なるほ！まぁレイアウト調整は必須

**Comment by ir77** [comment]
そこかーーー。
うちのiPhone6s Plusは拡大にしてるから4.7inchのが拡大されてるって感じだったのか……。

**Comment by ha1f** [comment]
メッチャそれですね！！！！！！

設定変更についても書いておきますか・・・

**Comment by ir77** [comment]
そのほうが丁寧やわ・・・
いろいろ謎が解けて良かった、、
